### ISSUE TITLE
Add slug field to Resource and Link models

### ISSUE THREAD

**Issue by cacarrara** [mochaoss/inspace#9]
> Slug is a newspaper term. A slug is a short label for something, containing only letters, numbers, underscores or hyphens. They’re generally used in URLs.

Django has an proper field for Slug: https://docs.djangoproject.com/en/1.11/ref/models/fields/#slugfield

The slug field on `Resource` and `Link` models should _slugify_  the `title` field.

**Comment by Pal0r** [comment]
Discussed and addressed in [Issue #9](https://github.com/mochaoss/inspace/issues/10).

**Comment by cacarrara** [comment]
Done in #25
